(()=>{
'use strict';
const data=globalThis.GLOSSARY_DATA,learnData=globalThis.GLOSSARY_LEARNING_DATA,app=document.getElementById('app');
if(!data||!learnData||!app)return;
const STORAGE_KEY='riyoshi_glossary_learning_v1',REVIEW_DATE='2026-07-17';
const states={safe:'安全',caution:'注意',danger:'危険'},tagOrder=['頻出','数値暗記','法令','感染症','消毒薬','成分','カタカナ語','アルファベット語','混同注意','過去問出題あり','監修確認中'];
const intervals={danger:[0,1,3],caution:[1,3,7],safe:[7,14]};
let learning=loadLearning(),screen='home',selectedCategory='全用語',selectedTags=new Set(),query='',listTerms=[],session=[],sessionIndex=0,revealed=false,quizState=null,assessedCurrent=false,sessionStats=null,returnScreen='home';
function esc(value){return String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]))}
function loadLearning(){try{const value=JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}');return value&&typeof value==='object'&&!Array.isArray(value)?value:{}}catch(_){return{}}}
function saveLearning(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(learning))}catch(_){}}
function stateKey(term){return `v136-${term.id}`}
function termState(term){const key=stateKey(term);if(learning[key])return learning[key];const old=learning[`v135-${term.id}`]||(term.legacyNumbers||[]).map(number=>learning[number]).find(Boolean);if(old){learning[key]={...old,history:Array.isArray(old.history)?old.history:[],quizCorrect:Number(old.quizCorrect)||0,quizWrong:Number(old.quizWrong)||0,studyCount:Number(old.studyCount)||0,stage:Number(old.stage)||0};saveLearning();return learning[key]}return null}
function today(){const parts=new Intl.DateTimeFormat('en',{timeZone:'Asia/Tokyo',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date()),get=type=>parts.find(part=>part.type===type).value;return `${get('year')}-${get('month')}-${get('day')}`}
function addDays(value,days){const [y,m,d]=value.split('-').map(Number),date=new Date(Date.UTC(y,m-1,d+days,12));return date.toISOString().slice(0,10)}
function dateTime(){return new Date().toISOString()}
function tags(term){const result=[];for(const [tag,names] of Object.entries(learnData.explicitTags||{})){if(names.includes(term.name))result.push(tag)}if(term.mixup?.length)result.push('混同注意');if(term.status==='監修確認中')result.push('監修確認中');return [...new Set(result)]}
function isDue(term,includeToday=true){const value=termState(term)?.nextReviewDate;if(!value)return false;return includeToday?value<=today():value<today()}
function stats(terms=data.terms){let safe=0,caution=0,danger=0,learned=0,due=0,correct=0,wrong=0,last='';for(const term of terms){const s=termState(term);if(!s)continue;if(states[s.status]){learned++;if(s.status==='safe')safe++;if(s.status==='caution')caution++;if(s.status==='danger')danger++}if(isDue(term,false))due++;correct+=Number(s.quizCorrect)||0;wrong+=Number(s.quizWrong)||0;if(s.lastStudyAt&&s.lastStudyAt>last)last=s.lastStudyAt}return{total:terms.length,learned,unlearned:terms.length-learned,safe,caution,danger,due,correct,wrong,rate:correct+wrong?Math.round(correct/(correct+wrong)*100):0,last}}
function statusSummary(terms){const s=stats(terms),pct=s.total?Math.round(s.learned/s.total*100):0;return `<section class="summary-card"><div class="ring" style="--progress:${pct}%"><span>${pct}%</span></div><div><div class="summary-label">学習進捗</div><div class="summary-main">${s.learned} / ${s.total}語</div><div class="summary-sub">学習済み ${s.learned}語　復習期限超過 ${s.due}語<br>確認問題正答率 ${s.correct+s.wrong?s.rate+'％':'未解答'}${s.last?`　最終 ${formatDate(s.last)}`:''}</div></div></section><section class="status-grid"><div class="status-box safe"><span class="status-dot"></span>安全<em>${s.safe}語</em></div><div class="status-box caution"><span class="status-dot"></span>注意<em>${s.caution}語</em></div><div class="status-box danger"><span class="status-dot"></span>危険<em>${s.danger}語</em></div><div class="status-box unlearned"><span class="status-dot"></span>未学習<em>${s.unlearned}語</em></div></section><div class="progress-line"><i style="width:${pct}%"></i></div>`}
function formatDate(value){if(!value)return'―';const date=new Date(value.length===10?value+'T00:00:00+09:00':value);return new Intl.DateTimeFormat('ja-JP',{timeZone:'Asia/Tokyo',month:'numeric',day:'numeric'}).format(date)}
function byCategory(category){return category==='全用語'?data.terms:data.terms.filter(term=>term.category===category)}
function modeTerms(mode){if(mode==='weak')return data.terms.filter(term=>['danger','caution'].includes(termState(term)?.status)).sort(prioritySort);if(mode==='unlearned')return data.terms.filter(term=>!termState(term)?.status);if(mode==='numeric')return data.terms.filter(term=>tags(term).includes('数値暗記'));if(mode==='confusion')return data.terms.filter(term=>tags(term).includes('混同注意'));if(mode==='reviewed')return data.terms.filter(term=>term.status!=='監修確認中');if(mode==='exam')return [...data.terms].sort(prioritySort);if(mode==='random')return shuffle([...data.terms]).slice(0,20);return todayTerms()}
function priority(term){const s=termState(term),due=s?.nextReviewDate||'9999-99-99',late=due<today(),todayDue=due===today();if(s?.status==='danger'&&late)return 0;if(s?.status==='danger'&&todayDue)return 1;if(s?.status==='caution'&&late)return 2;if(s?.status==='caution'&&todayDue)return 3;if(!s?.status)return 4;if(s?.status==='danger')return 5;if(s?.status==='caution')return 6;return 7}
function prioritySort(a,b){return priority(a)-priority(b)||(termState(a)?.nextReviewDate||'').localeCompare(termState(b)?.nextReviewDate||'')||a.id-b.id}
function todayTerms(){const ordered=[...data.terms].sort(prioritySort),picked=[],used=new Set();while(picked.length<10){let added=false;for(const term of ordered){if(used.has(term.id)||picked.some(row=>row.category===term.category&&priority(row)===priority(term)))continue;picked.push(term);used.add(term.id);added=true;if(picked.length===10)break}if(!added)break}for(const term of ordered){if(picked.length===10)break;if(!used.has(term.id)){picked.push(term);used.add(term.id)}}return picked}
function shuffle(items){for(let i=items.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[items[i],items[j]]=[items[j],items[i]]}return items}
function modeButton(icon,label,mode){return `<button class="mode-button" onclick="Glossary.startMode('${mode}')"><span class="mode-icon">${icon}</span><span>${label}</span></button>`}
function renderHome(){screen='home';app.innerHTML=`<h1 class="page-title">理容師国家試験 用語集</h1>${statusSummary(data.terms)}<h2 class="section-title">学習モード</h2><section class="mode-grid">${modeButton('▣','今日の10語','today')}${modeButton('↗','苦手用語','weak')}${modeButton('▢','未学習','unlearned')}${modeButton('⌑','数値基準','numeric')}${modeButton('△','混同注意','confusion')}${modeButton('⤨','ランダム20語','random')}</section><section class="minor-modes"><button class="minor-mode" onclick="Glossary.scrollCategories()">カテゴリ指定</button><button class="minor-mode" onclick="Glossary.startMode('exam')">試験直前総復習</button><button class="minor-mode" onclick="Glossary.startMode('reviewed')">監修済み用語だけ</button><button class="minor-mode" onclick="Glossary.showComparisons()">比較学習</button></section><div class="search-row"><input id="home-search" type="search" placeholder="用語を検索" aria-label="用語を検索"><button class="tag-toggle" onclick="Glossary.toggleTags()">◇ タグ</button></div><section id="tag-panel" class="tag-panel hidden">${tagOrder.map(tag=>`<button class="tag-chip" data-tag="${tag}" onclick="Glossary.toggleTag('${tag}',this)">${tag}</button>`).join('')}<button class="tag-chip" onclick="Glossary.openTags()">選択タグで表示</button><button class="tag-chip clear-tags" onclick="Glossary.clearTags()">タグ解除</button></section><h2 class="section-title" id="categories">カテゴリ</h2><section class="category-list">${data.categories.map(category=>{const terms=byCategory(category),s=stats(terms);return `<button class="category-row" onclick="Glossary.openCategory('${category}')"><span>${category}</span><span class="count">${terms.length}語</span><span class="review">要復習 ${s.caution+s.danger}語</span><span class="go">›</span></button>`}).join('')}</section><div class="sticky-start"><button onclick="Glossary.startMode('today')">今日の10語を始める</button></div>`;document.getElementById('home-search').addEventListener('change',event=>openList('検索結果',data.terms.filter(term=>matchesSearch(term,event.target.value))))}
function matchesSearch(term,value=query){const needle=String(value||'').trim().toLocaleLowerCase('ja');return !needle||[term.name,...(term.aliases||[])].join(' ').toLocaleLowerCase('ja').includes(needle)}
function filteredTerms(){return byCategory(selectedCategory).filter(term=>matchesSearch(term)&&[...selectedTags].every(tag=>tags(term).includes(tag)))}
function openList(title,terms=null){screen='list';returnScreen='home';listTerms=terms||filteredTerms();app.innerHTML=`<section class="view-head"><button onclick="Glossary.home()">‹</button><h1>${esc(title)}</h1><span></span></section>${statusSummary(listTerms)}<div class="list-tools"><input id="list-search" type="search" placeholder="この一覧を検索"><button onclick="Glossary.startVisible()">一覧から学習</button></div><div id="list-container">${listCards(listTerms)}</div>`;document.getElementById('list-search').addEventListener('input',event=>{const visible=listTerms.filter(term=>matchesSearch(term,event.target.value));document.getElementById('list-container').innerHTML=listCards(visible)})}
function listCards(terms){return terms.length?terms.map(term=>{const s=termState(term),due=isDue(term,false);return `<details class="term-card" id="term-${term.id}"><summary><span class="arrow">▶</span><span>${esc(term.name)}${due?'<br><span class="due-label">復習期限超過</span>':''}</span><span class="term-category">${esc(term.category)}</span></summary><div class="term-back">${termFields(term)}${sourceBlock(term)}${pastBlock(term)}<div class="assessment-inline">${assessmentButtons(term,s?.status,'inline')}</div><div class="next-review">次回復習日：${s?.nextReviewDate?formatDate(s.nextReviewDate):'未設定'}</div></div></details>`}).join(''):'<div class="empty">対象の用語はありません。</div>'}
function textField(label,value,extra=''){return value?`<div class="term-field ${extra}"><div class="term-label">${esc(label)}</div><div class="term-value">${esc(value)}</div></div>`:''}
function listField(label,values,extra=''){return values?.length?`<div class="term-field ${extra}"><div class="term-label">${esc(label)}</div><div class="term-value"><ul>${values.map(value=>`<li>${esc(value)}</li>`).join('')}</ul></div></div>`:''}
function termFields(term){return `${textField('定義',term.definition)}${term.aliases?.length?textField('別名・関連表記',term.aliases.join('／')):''}${Object.entries(term.special||{}).map(([label,value])=>textField(label,value)).join('')}${listField('試験の要点',term.exam)}${listField('混同注意',term.mixup,'mixup')}`}
function sourceBlock(term){const links=(term.sources||[]).map(source=>source.url?`<a href="${esc(source.url)}" target="_blank" rel="noopener">${esc(source.label)}</a>`:esc(source.label)).join('<br>');return `<details class="source-details"><summary>出典・監修状態</summary><div class="source-content">${esc(term.sourceText)}${links?`<br>${links}`:''}<br><span class="review-pill">${esc(term.status)}</span>　基準日：${REVIEW_DATE}</div></details>`}
function pastBlock(term){const links=learnData.pastLinks?.[term.id];return links?.length?`<div class="past-links"><div class="term-label">この用語が出題された過去問</div>${links.map(([label,url])=>`<a href="${esc(url)}">${esc(label)}</a>`).join('<br>')}</div>`:''}
function assessmentButtons(term,current,kind='session'){return Object.entries(states).map(([key,label])=>`<button class="${key}${current===key?' selected':''}" onclick="Glossary.assess(${term.id},'${key}','${kind}')">${key==='safe'?'🟢':key==='caution'?'🟡':'🔴'} ${label}</button>`).join('')}
function startMode(mode){let terms=modeTerms(mode),label={today:'今日の10語',weak:'苦手用語',unlearned:'未学習',numeric:'数値基準',confusion:'混同注意',random:'ランダム20語',exam:'試験直前総復習',reviewed:'監修済み用語だけ'}[mode]||'用語学習';if(mode==='weak'||mode==='unlearned'||mode==='numeric'||mode==='confusion'||mode==='reviewed'){openList(label,terms);return}if(mode==='exam')terms=terms.slice(0,50);startSession(terms,label)}
function startSession(terms,label='用語学習'){if(!terms.length){openList(label,[]);return}screen='session';session=terms;sessionIndex=0;sessionStats={label,studied:0,correct:0,wrong:0,safe:0,caution:0,danger:0};prepareTerm();renderSession()}
function prepareTerm(){revealed=false;quizState=null;assessedCurrent=false}
function currentTerm(){return session[sessionIndex]}
function renderSession(){const term=currentTerm(),s=termState(term),progress=Math.round(sessionIndex/session.length*100),question=learnData.questions?.[term.id];app.innerHTML=`<section class="view-head"><button onclick="Glossary.exitSession()">‹</button><h1>${esc(sessionStats.label)}</h1><button onclick="Glossary.home()">⌂</button></section><div class="study-count">${sessionIndex+1} / ${session.length}語</div><div class="study-progress"><i style="width:${progress}%"></i></div><section class="study-card"><div class="term-front"><div><div class="term-category">${esc(term.category)}</div><h2>${esc(term.name)}</h2><div class="tag-line">${tags(term).map(tag=>`<span class="mini-tag">${esc(tag)}</span>`).join('')}</div></div></div>${!revealed?'<button class="reveal-button" onclick="Glossary.reveal()">答えを確認</button>':`<div class="term-back">${termFields(term)}${sourceBlock(term)}${pastBlock(term)}</div>${question?quizHtml(term,question):assessmentArea(term,s)}${sessionNavigation()}`}</section>`}
function quizHtml(term,question){if(!quizState){const options=shuffle(question.choices.map((text,index)=>({text,correct:index===question.answer})));quizState={options,selected:null,answered:false,correct:false,assessed:false}}return `<section class="quiz"><h3>${esc(question.question)}</h3>${quizState.options.map((option,index)=>`<button class="quiz-choice ${quizState.selected===index?'selected ':''}${quizState.answered&&option.correct?'correct ':''}${quizState.answered&&quizState.selected===index&&!option.correct?'wrong ':''}" onclick="Glossary.chooseQuiz(${index})" ${quizState.answered?'disabled':''}>${index+1}．${esc(option.text)}</button>`).join('')}${!quizState.answered?'<button class="quiz-submit" onclick="Glossary.submitQuiz()">解答する</button>':`<div class="quiz-result">${quizState.correct?'正解です。':'不正解です。'}<br>${esc(question.explanation)}</div>${assessmentArea(term,termState(term))}`}</section>`}
function assessmentArea(term,s){return `<div class="assessment">${assessmentButtons(term,s?.status)}</div><div class="next-review">次回復習日：${s?.nextReviewDate?formatDate(s.nextReviewDate):'自己評価後に設定'}</div>`}
function sessionNavigation(){return `<div class="session-navigation"><button onclick="Glossary.previousTerm()">戻る</button><button class="session-next" onclick="Glossary.nextTerm()">${sessionIndex===session.length-1?'結果を見る':'次へ'}</button></div>`}
function reveal(){revealed=true;renderSession()}
function chooseQuiz(index){if(quizState&&!quizState.answered){quizState.selected=index;renderSession()}}
function submitQuiz(){if(!quizState||quizState.selected===null)return;const term=currentTerm(),correct=quizState.options[quizState.selected].correct;quizState.answered=true;quizState.correct=correct;recordQuiz(term,correct);if(correct)sessionStats.correct++;else{sessionStats.wrong++;setStatus(term,'danger',true);assessedCurrent=true;sessionStats.danger++}renderSession()}
function recordQuiz(term,correct){const key=stateKey(term),s=termState(term)||{};learning[key]={...s,quizCorrect:(Number(s.quizCorrect)||0)+(correct?1:0),quizWrong:(Number(s.quizWrong)||0)+(correct?0:1)};saveLearning()}
function setStatus(term,status,automatic=false){const key=stateKey(term),old=termState(term)||{},now=dateTime(),previous=old.status||'',same=previous===status,stage=same?Math.min((Number(old.stage)||0)+1,intervals[status].length-1):0,days=intervals[status][stage],rank={danger:1,caution:2,safe:3};learning[key]={...old,status,previousStudyAt:old.lastStudyAt||null,lastStudyAt:now,nextReviewDate:addDays(today(),days),stage,studyCount:(Number(old.studyCount)||0)+1,improved:previous?rank[status]>rank[previous]:false,history:[...(Array.isArray(old.history)?old.history:[]),{at:now,status,automatic}].slice(-50)};saveLearning();return learning[key]}
function assess(id,status,kind){const term=data.terms.find(row=>row.id===id);if(!term)return;if(screen==='session'&&assessedCurrent)return;if(screen==='session'&&quizState?.answered&&!quizState.correct&&status!=='danger')return;setStatus(term,status);if(screen==='session'){sessionStats[status]++;assessedCurrent=true;renderSession()}else if(screen==='list'){openList(selectedCategory==='全用語'?'用語一覧':selectedCategory,listTerms)}else renderHome()}
function nextTerm(){sessionStats.studied++;if(sessionIndex<session.length-1){sessionIndex++;prepareTerm();renderSession();scrollTo(0,0)}else renderResult()}
function previousTerm(){if(sessionIndex>0){sessionIndex--;prepareTerm();renderSession();scrollTo(0,0)}else renderHome()}
function renderResult(){screen='result';const due=session.filter(term=>isDue(term)).length;app.innerHTML=`<section class="view-head"><button onclick="Glossary.home()">‹</button><h1>学習結果</h1><span></span></section><section class="result-card"><h2>${esc(sessionStats.label)}</h2><div class="result-grid"><div>学習した用語<br>${sessionStats.studied}語</div><div>正解<br>${sessionStats.correct}問</div><div>不正解<br>${sessionStats.wrong}問</div><div>安全へ移動<br>${sessionStats.safe}語</div><div>注意のまま<br>${sessionStats.caution}語</div><div>危険へ戻った<br>${sessionStats.danger}語</div></div><p>次回復習予定 ${due}語</p><button class="next-button" onclick="Glossary.home()">用語集へ戻る</button></section>`}
function renderComparisons(){screen='compare';app.innerHTML=`<section class="view-head"><button onclick="Glossary.home()">‹</button><h1>比較学習</h1><span></span></section><div class="compare-list">${learnData.comparisons.map(group=>`<section class="compare-card"><h2>${esc(group.title)}</h2>${group.items.map(([name,difference])=>`<div class="compare-row"><span>${esc(name)}</span><span>${esc(difference)}</span></div>`).join('')}</section>`).join('')}</div>`}
function openHashTerm(){const match=location.hash.match(/^#term=(.+)$/);if(!match)return false;const name=decodeURIComponent(match[1]),term=data.terms.find(row=>row.name===name);if(!term)return false;openList('関連用語',[term]);setTimeout(()=>document.getElementById(`term-${term.id}`)?.setAttribute('open',''),0);return true}
globalThis.Glossary={home:renderHome,startMode,openCategory(category){selectedCategory=category;selectedTags.clear();query='';openList(category,byCategory(category))},scrollCategories(){document.getElementById('categories')?.scrollIntoView({behavior:'smooth'})},toggleTags(){document.getElementById('tag-panel')?.classList.toggle('hidden')},toggleTag(tag,button){button.classList.toggle('active');button.classList.contains('active')?selectedTags.add(tag):selectedTags.delete(tag)},openTags(){selectedCategory='全用語';openList([...selectedTags].join('・')||'全用語',filteredTerms())},clearTags(){selectedTags.clear();renderHome()},startVisible(){startSession(listTerms.slice(0,50),selectedCategory==='全用語'?'用語学習':selectedCategory)},showComparisons:renderComparisons,reveal,chooseQuiz,submitQuiz,assess,nextTerm,previousTerm,exitSession(){renderHome()}};
if(!openHashTerm())renderHome();
})();
