(()=>{
'use strict';
const data=globalThis.GLOSSARY_DATA,learnData=globalThis.GLOSSARY_LEARNING_DATA,quizData=globalThis.GLOSSARY_QUIZ_DATA,app=document.getElementById('app');
if(!data||!learnData||!quizData||!app)return;
const STORAGE_KEY='riyoshi_glossary_learning_v1',REVIEW_DATE='2026-07-17';
const states={safe:'安全',caution:'注意',danger:'危険'},tagOrder=['頻出','数値暗記','法令','感染症','消毒薬','成分','カタカナ語','アルファベット語','混同注意','過去問出題あり','監修確認中'];
const intervals={danger:[0,1,3],caution:[1,3,7],safe:[7,14]};
let learning=loadLearning(),screen='home',selectedCategory='全用語',selectedTags=new Set(),query='',listTerms=[],session=[],sessionIndex=0,revealed=false,quizState=null,assessedCurrent=false,sessionStats=null,returnScreen='home',todayQuizMode=false,statusSessionMode=false,todayAnswers=new Map(),sessionId='',expandedCategory='',evaluatedIds=new Set();
function esc(value){return String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]))}
function loadLearning(){try{const value=JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}');return value&&typeof value==='object'&&!Array.isArray(value)?value:{}}catch(_){return{}}}
function saveLearning(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(learning))}catch(_){}}
function stateKey(term){return `v136-${term.id}`}
function normalizeState(value={}){return{...value,history:Array.isArray(value.history)?value.history:[],recentAnswers:Array.isArray(value.recentAnswers)?value.recentAnswers.slice(-5):[],quizCorrect:Number(value.quizCorrect)||0,quizWrong:Number(value.quizWrong)||0,studyCount:Number(value.studyCount)||0,stage:Number(value.stage)||0}}
function termState(term){const key=stateKey(term);if(learning[key]){learning[key]=normalizeState(learning[key]);return learning[key]}const old=learning[`v135-${term.id}`]||(term.legacyNumbers||[]).map(number=>learning[number]).find(Boolean);if(old){learning[key]=normalizeState(old);saveLearning();return learning[key]}return null}
function resultType(row){return row?.finalResult||row?.result||''}
function performanceFor(term){const rows=(termState(term)?.recentAnswers||[]).slice(-5),types=rows.map(resultType),first=types.filter(x=>x==='first_correct').length,rate=rows.length?Math.round(first/rows.length*100):null,lastTwo=types.slice(-2),twoBad=lastTwo.length===2&&lastTwo.every(x=>x==='wrong'||x==='unable');let level='none';if(twoBad)level='danger';else if(rows.length===0)level='none';else if(rows.length<5){if(types.some(x=>x==='wrong'||x==='unable'))level='caution';else if(types.every(x=>x==='first_correct'))level='safe';else level='caution'}else level=rate>=80?'safe':'caution';return{level,rows,rate,types}}
function finalPriority(term){const s=termState(term),self=s?.status||'',ability=performanceFor(term).level;if(!self&&ability==='none')return'unlearned';if(self==='danger'||ability==='danger')return'danger';if(self==='caution'||ability==='caution')return'caution';return'safe'}
function today(){const parts=new Intl.DateTimeFormat('en',{timeZone:'Asia/Tokyo',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date()),get=type=>parts.find(part=>part.type===type).value;return `${get('year')}-${get('month')}-${get('day')}`}
function addDays(value,days){const [y,m,d]=value.split('-').map(Number),date=new Date(Date.UTC(y,m-1,d+days,12));return date.toISOString().slice(0,10)}
function dateTime(){return new Date().toISOString()}
function tags(term){const result=[];for(const [tag,names] of Object.entries(learnData.explicitTags||{})){if(names.includes(term.name))result.push(tag)}if(term.mixup?.length)result.push('混同注意');if(term.status==='監修確認中')result.push('監修確認中');return [...new Set(result)]}
function isDue(term,includeToday=true){const value=termState(term)?.nextReviewDate;if(!value)return false;return includeToday?value<=today():value<today()}
function latestAnswer(term){const rows=termState(term)?.recentAnswers||[];return rows.length?rows[rows.length-1]:null}
function statusBucket(term){const s=termState(term),latest=latestAnswer(term);if(resultType(latest)==='unable')return'unable';return states[s?.status]?s.status:'unlearned'}
function stats(terms=data.terms){let safe=0,caution=0,danger=0,unable=0,due=0,correct=0,wrong=0,last='';for(const term of terms){const s=termState(term),bucket=statusBucket(term);if(bucket==='safe')safe++;else if(bucket==='caution')caution++;else if(bucket==='danger')danger++;else if(bucket==='unable')unable++;if(s&&isDue(term,false))due++;correct+=Number(s?.quizCorrect)||0;wrong+=Number(s?.quizWrong)||0;if(s?.lastStudyAt&&s.lastStudyAt>last)last=s.lastStudyAt}const learned=safe+caution+danger+unable,unlearned=terms.length-learned;return{total:terms.length,learned,unlearned,safe,caution,danger,unable,due,correct,wrong,rate:correct+wrong?Math.round(correct/(correct+wrong)*100):0,last}}
function statusSummary(terms,categoryIndex=null){const s=stats(terms),pct=s.total?Math.round(s.learned/s.total*100):0,action=status=>categoryIndex===null?`Glossary.startStatus('${status}')`:`Glossary.startCategoryStatus(${categoryIndex},'${status}')`;return `<section class="summary-card"><div class="ring" style="--progress:${pct}%"><span>${pct}%</span></div><div><div class="summary-label">学習進捗</div><div class="summary-main">${s.learned} / ${s.total}語</div><div class="summary-sub">学習済み ${s.learned}語　未学習 ${s.unlearned}語<br>確認問題正答率 ${s.correct+s.wrong?s.rate+'％':'未解答'}</div></div></section><section class="status-grid"><button type="button" class="status-box safe" onclick="${action('safe')}" aria-label="安全 ${s.safe}語を復習"><span class="status-dot"></span>安全<em>${s.safe}語</em></button><button type="button" class="status-box caution" onclick="${action('caution')}" aria-label="注意 ${s.caution}語を復習"><span class="status-dot"></span>注意<em>${s.caution}語</em></button><button type="button" class="status-box danger" onclick="${action('danger')}" aria-label="危険 ${s.danger}語を復習"><span class="status-dot"></span>危険<em>${s.danger}語</em></button><button type="button" class="status-box unable" onclick="${action('unable')}" aria-label="無理 ${s.unable}語を復習"><span class="status-bookmark" aria-hidden="true">🔖</span>無理<em>${s.unable}語</em></button></section><div class="progress-line"><i style="width:${pct}%"></i></div>`}
function summaryTerms(){return screen==='list'?listTerms:data.terms}
function dateSortValue(value,fallback='9999-99-99'){return value||fallback}
function statusSort(status){return (a,b)=>{const sa=termState(a)||{},sb=termState(b)||{},lateA=sa.nextReviewDate&&sa.nextReviewDate<today()?0:1,lateB=sb.nextReviewDate&&sb.nextReviewDate<today()?0:1;if(status==='safe')return dateSortValue(sa.nextReviewDate).localeCompare(dateSortValue(sb.nextReviewDate))||dateSortValue(sa.lastStudyAt).localeCompare(dateSortValue(sb.lastStudyAt))||a.id-b.id;if(status==='unable'){const ua=latestAnswer(a)?.answeredAt||'9999-99-99',ub=latestAnswer(b)?.answeredAt||'9999-99-99';return lateA-lateB||ua.localeCompare(ub)||dateSortValue(sa.nextReviewDate).localeCompare(dateSortValue(sb.nextReviewDate))||a.id-b.id}return lateA-lateB||dateSortValue(sa.nextReviewDate).localeCompare(dateSortValue(sb.nextReviewDate))||dateSortValue(sa.lastStudyAt).localeCompare(dateSortValue(sb.lastStudyAt))||a.id-b.id}}
function categoryRoundRobin(terms){const groups=data.categories.map(category=>terms.filter(term=>term.category===category)),result=[];let added=true;while(added){added=false;for(const group of groups){if(group.length){result.push(group.shift());added=true}}}return result}
function showStatusMessage(message){document.querySelector('.status-message')?.remove();const box=document.createElement('div');box.className='status-message';box.setAttribute('role','status');box.innerHTML=`<span>${esc(message)}</span><button type="button" aria-label="閉じる">×</button>`;box.querySelector('button').addEventListener('click',()=>box.remove());app.appendChild(box);box.querySelector('button').focus()}
function startStatusFrom(source,status){const seen=new Set(),matching=source.filter(term=>{if(seen.has(term.id))return false;seen.add(term.id);return statusBucket(term)===status}),ordered=matching.sort(statusSort(status)),labels={safe:'安全の復習',caution:'注意の復習',danger:'危険の復習',unable:'無理の復習'},empty={safe:'安全に該当する用語はありません',caution:'注意に該当する用語はありません',danger:'危険に該当する用語はありません',unable:'無理に該当する用語はありません'};if(!ordered.length){showStatusMessage(empty[status]);return}startSession(ordered,labels[status],true,status)}
function startStatus(status){startStatusFrom(summaryTerms(),status)}
function formatDate(value){if(!value)return'―';const date=new Date(value.length===10?value+'T00:00:00+09:00':value);return new Intl.DateTimeFormat('ja-JP',{timeZone:'Asia/Tokyo',month:'numeric',day:'numeric'}).format(date)}
function byCategory(category){return category==='全用語'?data.terms:data.terms.filter(term=>term.category===category)}
function languagePriority(term){if(isDue(term,false))return 0;if(resultType(latestAnswer(term))==='unable')return 1;const level=finalPriority(term);return{danger:2,caution:3,unlearned:4,safe:5}[level]??6}
function languageSort(locale){return(a,b)=>languagePriority(a)-languagePriority(b)||a.name.localeCompare(b.name,locale,{sensitivity:'base'})||a.id-b.id}
function modeTerms(mode){if(mode==='katakana')return data.terms.filter(term=>tags(term).includes('カタカナ語')).sort(languageSort('ja'));if(mode==='alphabet')return data.terms.filter(term=>tags(term).includes('アルファベット語')).sort(languageSort('en'));if(mode==='numeric')return data.terms.filter(term=>tags(term).includes('数値暗記')).sort(languageSort('ja'));if(mode==='confusion')return data.terms.filter(term=>tags(term).includes('混同注意'));if(mode==='exam')return [...data.terms].sort(prioritySort);return todayTerms()}
function priority(term){const s=termState(term),due=s?.nextReviewDate||'9999-99-99',late=due<today(),todayDue=due===today(),final=finalPriority(term),perf=performanceFor(term),last=resultType(perf.rows.at(-1));if(final==='danger'&&late)return 0;if(perf.rows.length>=2&&perf.rows.slice(-2).every(x=>['wrong','unable'].includes(resultType(x))))return 1;if(last==='unable')return 2;if(final==='danger'&&todayDue)return 3;if(final==='caution'&&late)return 4;if(final==='caution'&&todayDue)return 5;if(final==='unlearned')return 6;return 7}
function prioritySort(a,b){return priority(a)-priority(b)||(termState(a)?.nextReviewDate||'').localeCompare(termState(b)?.nextReviewDate||'')||a.id-b.id}
function todayTerms(){const ordered=[...data.terms].sort(prioritySort),picked=[],used=new Set();while(picked.length<10){let added=false;for(const term of ordered){if(used.has(term.id)||picked.some(row=>row.category===term.category&&priority(row)===priority(term)))continue;picked.push(term);used.add(term.id);added=true;if(picked.length===10)break}if(!added)break}for(const term of ordered){if(picked.length===10)break;if(!used.has(term.id)){picked.push(term);used.add(term.id)}}return picked}
function shuffle(items){for(let i=items.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[items[i],items[j]]=[items[j],items[i]]}return items}
function modeButton(icon,label,mode){return `<button class="mode-button" onclick="Glossary.startMode('${mode}')"><span class="mode-icon">${icon}</span><span>${label}</span></button>`}
function syncFloatingNav(){const back=document.getElementById('glossaryBack');if(back)back.hidden=screen==='home'}
function categoryAccordion(){return data.categories.map((category,index)=>{const terms=byCategory(category),s=stats(terms),open=expandedCategory===category,panelId=`category-panel-${index}`,panel=open?`<div class="category-panel" id="${panelId}">${statusSummary(terms,index)}<div class="list-tools"><button type="button" onclick="Glossary.startCategoryAll(${index})">このカテゴリを3択で学習</button></div><div class="category-terms">${listCards(terms)}</div></div>`:`<div id="${panelId}" hidden></div>`;return `<section class="category-item"><button type="button" class="category-row" data-category-index="${index}" onclick="Glossary.toggleCategory(${index})" aria-expanded="${open}" aria-controls="${panelId}"><span>${esc(category)}</span><span class="count">${terms.length}語</span><span class="review">要復習 ${s.caution+s.danger+s.unable}語</span><span class="go" aria-hidden="true">${open?'▼':'▶'}</span></button>${panel}</section>`}).join('')}
function renderHome(){screen='home';app.innerHTML=`${statusSummary(data.terms)}<h2 class="section-title">学習モード</h2><section class="mode-grid">${modeButton('カ','カタカナ','katakana')}${modeButton('⌑','数値暗記','numeric')}${modeButton('△','混同注意','confusion')}${modeButton('A','英字略語','alphabet')}${modeButton('⇄','比較学習','comparison')}</section><h2 class="section-title" id="categories">一覧から学習</h2><section class="category-list">${categoryAccordion()}</section><section class="glossary-reset"><button onclick="Glossary.resetLearning()">用語集の学習履歴をリセット</button></section><div class="sticky-start"><button onclick="Glossary.startMode('today')">今日の10語を始める</button></div>`;syncFloatingNav()}
function matchesSearch(term,value=query){const needle=String(value||'').trim().toLocaleLowerCase('ja');return !needle||[term.name,...(term.aliases||[])].join(' ').toLocaleLowerCase('ja').includes(needle)}
function filteredTerms(){return byCategory(selectedCategory).filter(term=>matchesSearch(term)&&[...selectedTags].every(tag=>tags(term).includes(tag)))}
function openList(title,terms=null){screen='list';returnScreen='home';listTerms=terms||filteredTerms();app.innerHTML=`<section class="view-head"><span></span><h1>${esc(title)}</h1><span></span></section>${statusSummary(listTerms)}<div class="list-tools"><button onclick="Glossary.startVisible()">3択で学習</button></div><div id="list-container">${listCards(listTerms)}</div>`;syncFloatingNav()}
function listCards(terms){return terms.length?terms.map(term=>{const s=termState(term),due=isDue(term,false);return `<details class="term-card" id="term-${term.id}"><summary><span class="arrow">▶</span><span>${esc(term.name)}${due?'<br><span class="due-label">復習期限超過</span>':''}</span><span class="term-category">${esc(term.category)}</span></summary><div class="term-back">${termFields(term)}${sourceBlock(term)}${pastBlock(term)}<div class="assessment-inline">${assessmentButtons(term,s?.status,'inline')}</div><div class="next-review">次回復習日：${s?.nextReviewDate?formatDate(s.nextReviewDate):'未設定'}</div></div></details>`}).join(''):'<div class="empty">対象の用語はありません。</div>'}
function textField(label,value,extra=''){return value?`<div class="term-field ${extra}"><div class="term-label">${esc(label)}</div><div class="term-value">${esc(value)}</div></div>`:''}
function listField(label,values,extra=''){return values?.length?`<div class="term-field ${extra}"><div class="term-label">${esc(label)}</div><div class="term-value"><ul>${values.map(value=>`<li>${esc(value)}</li>`).join('')}</ul></div></div>`:''}
function termFields(term){return `${textField('定義',term.definition)}${term.aliases?.length?textField('別名・関連表記',term.aliases.join('／')):''}${Object.entries(term.special||{}).map(([label,value])=>textField(label,value)).join('')}${listField('試験の要点',term.exam,'exam-points')}${listField('混同注意',term.mixup)}`}
function sourceBlock(term){const links=(term.sources||[]).map(source=>source.url?`<a href="${esc(source.url)}" target="_blank" rel="noopener">${esc(source.label)}</a>`:esc(source.label)).join('<br>');return `<details class="source-details"><summary>出典・監修状態</summary><div class="source-content">${esc(term.sourceText)}${links?`<br>${links}`:''}<br><span class="review-pill">${esc(term.status)}</span>　基準日：${REVIEW_DATE}</div></details>`}
function pastBlock(term){const links=learnData.pastLinks?.[term.id];return links?.length?`<div class="past-links"><div class="term-label">この用語が出題された過去問</div>${links.map(([label,url])=>`<a href="${esc(url)}">${esc(label)}</a>`).join('<br>')}</div>`:''}
function assessmentButtons(term,current,kind='session'){return Object.entries(states).map(([key,label])=>`<button class="${key}${current===key?' selected':''}" onclick="Glossary.assess(${term.id},'${key}','${kind}')">${key==='safe'?'🟢':key==='caution'?'🟡':'🔴'} ${label}</button>`).join('')}
function startMode(mode){if(mode==='comparison'){renderComparisons();return}let terms=modeTerms(mode),label={today:'今日の10語',katakana:'カタカナ',alphabet:'英字略語',numeric:'数値暗記',confusion:'混同注意'}[mode]||'用語学習';if(['katakana','alphabet','numeric','confusion'].includes(mode)){if(!terms.length){const empty={katakana:'カタカナに該当する用語はありません',alphabet:'英字略語に該当する用語はありません',numeric:'数値暗記に該当する用語はありません',confusion:'混同注意に該当する用語はありません'};showStatusMessage(empty[mode]);return}startSession(terms,label,true);return}startSession(terms,label)}
function startSession(terms,label='用語学習',useThreeChoice=false,sourceStatus=''){if(!terms.length){openList(label,[]);return}screen='session';session=[...terms];sessionIndex=0;sessionId=`gs-${Date.now()}-${Math.random().toString(36).slice(2,8)}`;statusSessionMode=Boolean(sourceStatus);todayQuizMode=label==='今日の10語'||useThreeChoice;todayAnswers=new Map();evaluatedIds=new Set();sessionStats={label,sourceStatus,studied:0,correct:0,firstCorrect:0,secondCorrect:0,wrong:0,unable:0,safe:0,caution:0,danger:0};prepareTerm();renderSession()}
function prepareTerm(){revealed=false;quizState=null;assessedCurrent=false}
function currentTerm(){return session[sessionIndex]}
function renderSession(){const term=currentTerm(),s=termState(term),progress=Math.round(sessionIndex/session.length*100),question=learnData.questions?.[term.id];app.innerHTML=`<section class="view-head"><span></span><h1>${esc(sessionStats.label)}</h1><span></span></section><div class="study-count">${sessionIndex+1} / ${session.length}語</div><div class="study-progress"><i style="width:${progress}%"></i></div><section class="study-card"><div class="term-front"><div><div class="term-category">${esc(term.category)}</div><h2>${esc(term.name)}</h2></div></div>${todayQuizMode?todayQuizHtml(term):!revealed?'<button class="reveal-button" onclick="Glossary.reveal()">答えを確認</button>':`<div class="term-back">${termFields(term)}${sourceBlock(term)}${pastBlock(term)}</div>${question?quizHtml(term,question):assessmentArea(term,s)}${sessionNavigation()}`}</section>`;syncFloatingNav()}
function todayResponse(term=currentTerm()){if(todayAnswers.has(term.id))return todayAnswers.get(term.id);const question=quizData.questions?.[term.id],distractors=question?shuffle([...question.distractors]).slice(0,2):[],options=question?shuffle([{text:question.correct,correct:true},...distractors.map(text=>({text,correct:false}))]):[],response={question:question?.question||'',source:question?.source||'',options,hold:!question,attempts:[],completed:false,autoStatus:'',currentStatus:'',counted:false,originalResult:'',finalResult:'',unable:false,unableTiming:'',recorded:false};todayAnswers.set(term.id,response);return response}
function performanceHtml(term,response){const perf=performanceFor(term),s=termState(term),symbols={first_correct:'○',second_correct:'△',wrong:'×',unable:'🔖'},label={safe:'安全候補',caution:'注意',danger:'危険',none:'データなし'}[perf.level],final={safe:'安全相当',caution:'注意相当',danger:'危険相当',unlearned:'未学習'}[finalPriority(term)],notice=response.unable?'自力回答不能として記録されています':s?.status==='safe'&&['caution','danger'].includes(perf.level)?'実績では要注意':['caution','danger'].includes(s?.status)&&perf.level==='safe'?'実績は改善傾向です':'';return `<details class="performance-details"><summary>正答実績</summary><div>自己評価：${states[s?.status]||'未設定'}<br>実力評価：${label}<br>直近5回：${perf.rows.map(x=>symbols[resultType(x)]||'').join(' ')||'記録なし'}<br>1回目正解率：${perf.rate===null?'未算出':perf.rate+'％'}<br>復習優先度：${final}<br>次回復習日：${s?.nextReviewDate?formatDate(s.nextReviewDate):'未設定'}${notice?`<br><span class="performance-notice">${notice}</span>`:''}</div></details>`}
function todayQuizHtml(term){const response=todayResponse(term),wrong=new Set(response.attempts.filter(index=>!response.options[index].correct));return `<section class="quiz today-quiz"><h3>${esc(response.question)}</h3>${response.options.map((option,index)=>`<button class="quiz-choice ${wrong.has(index)?'wrong ':''}${response.completed&&option.correct?'correct ':''}" onclick="Glossary.chooseToday(${index})" ${(response.completed||wrong.has(index))?'disabled':''}>${index+1}．${esc(option.text)}</button>`).join('')}<button class="unable-button" aria-label="自力で回答できない" onclick="Glossary.markUnable()" ${response.unable?'disabled':''}>🔖 無理</button>${response.attempts.length===1&&!response.completed?'<div class="quiz-result retry">不正解です。残りの選択肢から、もう一度選んでください。</div>':''}${response.completed?`<div class="quiz-result">${response.unable?'自力で回答できなかったものとして記録しました。':response.autoStatus==='safe'?'1回目で正解です。':response.autoStatus==='caution'?'2回目で正解です。':'正解を確認してください。'}</div><div class="term-back">${termFields(term)}${sourceBlock(term)}${pastBlock(term)}</div>${todayAssessmentArea(term,response)}${performanceHtml(term,response)}`:''}</section>${sessionNavigation()}`}
function finalResultFor(response){if(response.unable)return'unable';const last=response.attempts.at(-1),correct=response.options[last]?.correct;if(correct)return response.attempts.length===1?'first_correct':'second_correct';return response.attempts.length>=2?'wrong':''}
function saveRecentAnswer(term,response){const key=stateKey(term),s=termState(term)||{},result=finalResultFor(response);if(!result)return;const rows=[...(s.recentAnswers||[])],existing=rows.findIndex(x=>x.sessionId===sessionId&&x.termId===term.id),row={id:`${sessionId}-${term.id}`,sessionId,termId:term.id,answeredAt:dateTime(),mode:sessionStats.label,firstChoice:response.attempts[0]??null,secondChoice:response.attempts[1]??null,originalResult:response.originalResult||result,finalResult:result,unable:response.unable,unableTiming:response.unableTiming||'',automaticStatus:response.autoStatus,manualStatus:response.currentStatus||response.autoStatus,reason:response.unable?'利用者が自力回答不能を申告':''};if(existing>=0)rows[existing]={...rows[existing],...row};else rows.push(row);learning[key]={...s,recentAnswers:rows.slice(-5)};saveLearning();response.recorded=true}
function applyQuizOutcome(term,response){const previous=response.finalResult||'',next=finalResultFor(response);if(!next||previous===next)return;if(previous){if(previous==='first_correct')sessionStats.firstCorrect--;else if(previous==='second_correct')sessionStats.secondCorrect--;else if(previous==='wrong')sessionStats.wrong--;else if(previous==='unable')sessionStats.unable--;adjustQuizTotals(term,previous,-1)}if(next==='first_correct')sessionStats.firstCorrect++;else if(next==='second_correct')sessionStats.secondCorrect++;else if(next==='wrong')sessionStats.wrong++;else sessionStats.unable++;adjustQuizTotals(term,next,1);response.finalResult=next;saveRecentAnswer(term,response)}
function adjustQuizTotals(term,result,delta){const key=stateKey(term),s=termState(term)||{},correct=result==='first_correct'||result==='second_correct';learning[key]={...s,quizCorrect:Math.max(0,(Number(s.quizCorrect)||0)+(correct?delta:0)),quizWrong:Math.max(0,(Number(s.quizWrong)||0)+(correct?0:delta))};saveLearning()}
function chooseToday(index){const term=currentTerm(),response=todayResponse(term);if(response.completed||response.attempts.includes(index))return;response.attempts.push(index);const correct=response.options[index].correct;if(correct||response.attempts.length===2){response.completed=true;response.originalResult=correct?(response.attempts.length===1?'first_correct':'second_correct'):'wrong';response.autoStatus=correct?(response.attempts.length===1?'safe':'caution'):'danger';response.currentStatus=response.autoStatus;applyQuizOutcome(term,response);setStatus(term,response.autoStatus,true,`3択:${response.originalResult}`);sessionStats[response.autoStatus]++;evaluatedIds.add(term.id)}renderSession()}
function markUnable(){const term=currentTerm(),response=todayResponse(term);if(response.unable)return;response.unable=true;response.unableTiming=response.completed?'after':'before';if(!response.completed){response.completed=true;response.originalResult='unable'}response.autoStatus='danger';if(response.currentStatus&&sessionStats[response.currentStatus]>0)sessionStats[response.currentStatus]--;response.currentStatus='danger';sessionStats.danger++;applyQuizOutcome(term,response);setStatus(term,'danger',true,'利用者が自力回答不能を申告');evaluatedIds.add(term.id);renderSession()}
function todayAssessmentArea(term,response){const s=termState(term);return `<div class="assessment">${Object.entries(states).map(([key,label])=>`<button class="${key}${response.currentStatus===key?' selected':''}" onclick="Glossary.overrideToday('${key}')">${key==='safe'?'🟢':key==='caution'?'🟡':'🔴'} ${label}</button>`).join('')}</div><div class="next-review">次回復習日：${s?.nextReviewDate?formatDate(s.nextReviewDate):'自己評価後に設定'}</div>`}
function overrideToday(status){const term=currentTerm(),response=todayResponse(term);if(!response.completed||!states[status])return;if(response.currentStatus!==status){sessionStats[response.currentStatus]=Math.max(0,sessionStats[response.currentStatus]-1);sessionStats[status]++;response.currentStatus=status;setStatus(term,status,false,'手動自己評価を優先');saveRecentAnswer(term,response)}renderSession()}
function quizHtml(term,question){if(!quizState){const options=shuffle(question.choices.map((text,index)=>({text,correct:index===question.answer})));quizState={options,selected:null,answered:false,correct:false,assessed:false}}return `<section class="quiz"><h3>${esc(question.question)}</h3>${quizState.options.map((option,index)=>`<button class="quiz-choice ${quizState.selected===index?'selected ':''}${quizState.answered&&option.correct?'correct ':''}${quizState.answered&&quizState.selected===index&&!option.correct?'wrong ':''}" onclick="Glossary.chooseQuiz(${index})" ${quizState.answered?'disabled':''}>${index+1}．${esc(option.text)}</button>`).join('')}${!quizState.answered?'<button class="quiz-submit" onclick="Glossary.submitQuiz()">解答する</button>':`<div class="quiz-result">${quizState.correct?'正解です。':'不正解です。'}<br>${esc(question.explanation)}</div>${assessmentArea(term,termState(term))}`}</section>`}
function assessmentArea(term,s){return `<div class="assessment">${assessmentButtons(term,s?.status)}</div><div class="next-review">次回復習日：${s?.nextReviewDate?formatDate(s.nextReviewDate):'自己評価後に設定'}</div>`}
function sessionNavigation(){return `<div class="session-navigation"><button onclick="Glossary.previousTerm()">前の用語</button><button class="session-next" onclick="Glossary.nextTerm()">${sessionIndex===session.length-1?'結果を見る':'次へ'}</button></div>`}
function reveal(){revealed=true;renderSession()}
function chooseQuiz(index){if(quizState&&!quizState.answered){quizState.selected=index;renderSession()}}
function submitQuiz(){if(!quizState||quizState.selected===null)return;const term=currentTerm(),correct=quizState.options[quizState.selected].correct;quizState.answered=true;quizState.correct=correct;recordQuiz(term,correct);if(correct)sessionStats.correct++;else{sessionStats.wrong++;setStatus(term,'danger',true);assessedCurrent=true;sessionStats.danger++}renderSession()}
function recordQuiz(term,correct){const key=stateKey(term),s=termState(term)||{};learning[key]={...s,quizCorrect:(Number(s.quizCorrect)||0)+(correct?1:0),quizWrong:(Number(s.quizWrong)||0)+(correct?0:1)};saveLearning()}
function setStatus(term,status,automatic=false,reason=''){const key=stateKey(term),old=termState(term)||{},now=dateTime(),previous=old.status||'',same=previous===status,ability=performanceFor(term).level,rank={danger:1,caution:2,safe:3},effective=rank[ability]&&rank[ability]<rank[status]?ability:status,stage=same?Math.min((Number(old.stage)||0)+1,intervals[effective].length-1):0,days=intervals[effective][stage];learning[key]={...old,status,performanceLevel:ability,reviewPriority:effective,previousStudyAt:old.lastStudyAt||null,lastStudyAt:now,nextReviewDate:addDays(today(),days),stage,studyCount:(Number(old.studyCount)||0)+1,improved:previous?rank[status]>rank[previous]:false,history:[...(Array.isArray(old.history)?old.history:[]),{at:now,status,automatic,performanceLevel:ability,reviewPriority:effective,reason}].slice(-50)};saveLearning();return learning[key]}
function assess(id,status,kind){const term=data.terms.find(row=>row.id===id);if(!term)return;if(screen==='session'&&assessedCurrent)return;if(screen==='session'&&quizState?.answered&&!quizState.correct&&status!=='danger')return;setStatus(term,status);if(screen==='session'){sessionStats[status]++;assessedCurrent=true;evaluatedIds.add(term.id);renderSession()}else if(screen==='list'){openList(selectedCategory==='全用語'?'用語一覧':selectedCategory,listTerms)}else renderHome()}
function nextTerm(){if(todayQuizMode){const response=todayResponse();if(response.completed&&!response.counted){sessionStats.studied++;response.counted=true;saveRecentAnswer(currentTerm(),response)}}else sessionStats.studied++;if(sessionIndex<session.length-1){sessionIndex++;prepareTerm();renderSession();scrollTo(0,0)}else renderResult()}
function previousTerm(){if(sessionIndex>0){sessionIndex--;prepareTerm();renderSession();scrollTo(0,0)}else renderHome()}
function renderResult(){screen='result';const unanswered=Math.max(0,session.length-sessionStats.studied),final={safe:0,caution:0,danger:0};for(const term of session){if(!evaluatedIds.has(term.id))continue;const status=termState(term)?.status;if(final[status]!==undefined)final[status]++}app.innerHTML=`<section class="view-head"><span></span><h1>学習結果</h1><span></span></section><section class="result-card"><h2>${esc(sessionStats.label)}</h2><div class="result-grid"><div>学習した用語<br>${sessionStats.studied}語</div><div>自力で正解<br>${sessionStats.firstCorrect}問</div><div>2回目で正解<br>${sessionStats.secondCorrect}問</div><div>不正解<br>${sessionStats.wrong}問</div><div>🔖 無理<br>${sessionStats.unable}問</div><div>未回答<br>${unanswered}語</div><div>最終評価：安全<br>${final.safe}語</div><div>最終評価：注意<br>${final.caution}語</div><div>最終評価：危険<br>${final.danger}語</div></div><button class="next-button" onclick="Glossary.home()">用語集へ戻る</button></section>`;syncFloatingNav()}

function resetLearning(){if(!confirm('用語集の安全・注意・危険、解答履歴、復習予定をすべて削除します。この操作は元に戻せません。'))return;learning={};try{localStorage.removeItem(STORAGE_KEY)}catch(_){}renderHome()}
function renderComparisons(){screen='compare';app.innerHTML=`<section class="view-head"><span></span><h1>比較学習</h1><span></span></section><div class="compare-list">${learnData.comparisons.map(group=>`<section class="compare-card"><h2>${esc(group.title)}</h2>${group.items.map(([name,difference])=>`<div class="compare-row"><span>${esc(name)}</span><span>${esc(difference)}</span></div>`).join('')}</section>`).join('')}</div>`;syncFloatingNav()}
function openHashTerm(){const match=location.hash.match(/^#term=(.+)$/);if(!match)return false;const name=decodeURIComponent(match[1]),term=data.terms.find(row=>row.name===name);if(!term)return false;openList('関連用語',[term]);setTimeout(()=>document.getElementById(`term-${term.id}`)?.setAttribute('open',''),0);return true}
globalThis.Glossary={home:renderHome,back(){if(screen!=='home')renderHome()},startMode,startStatus,startCategoryStatus(index,status){const category=data.categories[index];if(category===undefined)return;expandedCategory=category;startStatusFrom(byCategory(category),status)},toggleCategory(index){const category=data.categories[index];if(category===undefined)return;const anchor=document.querySelector(`[data-category-index="${index}"]`),top=anchor?.getBoundingClientRect?.().top;expandedCategory=expandedCategory===category?'':category;renderHome();if(Number.isFinite(top))setTimeout(()=>{const next=document.querySelector(`[data-category-index="${index}"]`);if(next?.getBoundingClientRect)scrollBy(0,next.getBoundingClientRect().top-top)},0)},openCategory(category){const index=data.categories.indexOf(category);if(index>=0)this.toggleCategory(index)},startCategoryAll(index){const category=data.categories[index];if(category===undefined)return;expandedCategory=category;selectedCategory=category;listTerms=byCategory(category).map((term,order)=>({term,order})).sort((a,b)=>languagePriority(a.term)-languagePriority(b.term)||a.order-b.order).map(row=>row.term);startSession(listTerms,category,true)},scrollCategories(){document.getElementById('categories')?.scrollIntoView({behavior:'smooth'})},toggleTags(){document.getElementById('tag-panel')?.classList.toggle('hidden')},toggleTag(tag,button){button.classList.toggle('active');button.classList.contains('active')?selectedTags.add(tag):selectedTags.delete(tag)},openTags(){selectedCategory='全用語';openList([...selectedTags].join('・')||'全用語',filteredTerms())},clearTags(){selectedTags.clear();renderHome()},startVisible(){startSession(listTerms,selectedCategory==='全用語'?'用語学習':selectedCategory,true)},showComparisons:renderComparisons,reveal,chooseQuiz,submitQuiz,chooseToday,markUnable,overrideToday,assess,nextTerm,previousTerm,resetLearning,exitSession(){renderHome()}};
if(!openHashTerm())renderHome();
})();
