/* 2026-07-16 カタカナ・略語・成分・人体部位の重点解説 */
(()=>{
const ABBR={
 SARS:['Severe Acute Respiratory Syndrome','重症急性呼吸器症候群'],MERS:['Middle East Respiratory Syndrome','中東呼吸器症候群'],SFTS:['Severe Fever with Thrombocytopenia Syndrome','重症熱性血小板減少症候群'],RSV:['Respiratory Syncytial Virus','RSウイルス'],RS:['Respiratory Syncytial','呼吸器合胞体性'],HBV:['Hepatitis B Virus','B型肝炎ウイルス'],HCV:['Hepatitis C Virus','C型肝炎ウイルス'],HIV:['Human Immunodeficiency Virus','ヒト免疫不全ウイルス'],AIDS:['Acquired Immunodeficiency Syndrome','後天性免疫不全症候群'],MRSA:['Methicillin-resistant Staphylococcus aureus','メチシリン耐性黄色ブドウ球菌'],COVID:['Coronavirus Disease','コロナウイルス症'],H5N1:['Influenza A virus subtype H5N1','A型インフルエンザウイルスH5N1亜型'],H7N9:['Influenza A virus subtype H7N9','A型インフルエンザウイルスH7N9亜型'],'E型肝炎':['Hepatitis E','E型肝炎ウイルスによる肝炎'],'A型肝炎':['Hepatitis A','A型肝炎ウイルスによる肝炎'],'Q熱':['Q fever','Coxiella burnetii による人畜共通感染症'],'Bウイルス病':['B virus disease','マカク属サルが保有するBウイルスによる感染症'],'A群溶血性レンサ球菌咽頭炎':['Group A streptococcal pharyngitis','A群レンサ球菌による咽頭炎'],WHO:['World Health Organization','世界保健機関'],QOL:['Quality of Life','生活の質'],BMI:['Body Mass Index','体格指数。体重kg÷身長m÷身長m'],BCG:['Bacille Calmette-Guérin','結核予防に用いる弱毒生ワクチン'],DNA:['Deoxyribonucleic Acid','デオキシリボ核酸'],RNA:['Ribonucleic Acid','リボ核酸'],HPV:['Human Papillomavirus','ヒトパピローマウイルス'],PPE:['Personal Protective Equipment','個人防護具'],VDT:['Visual Display Terminals','画像表示端末。現在は情報機器作業として扱われる'],UV:['Ultraviolet','紫外線'],PG:['Propylene Glycol','プロピレングリコール。保湿・溶剤等に用いられる'],BG:['Butylene Glycol','1,3-ブチレングリコール。保湿・溶剤等に用いられる'],pH:['potential of Hydrogen','水溶液の酸性・中性・アルカリ性の程度を表す指標'],Na:['Natrium (sodium)','ナトリウムの元素記号']
};
const ROLE={
 'エタノール':'溶剤、清涼感の付与、濃度と用途によっては消毒に用いる。汚れが残ると消毒効果が低下するため、洗浄後に用いる。','消毒用エタノール':'エタノールのタンパク変性等を利用する消毒剤。火気、揮発、密閉保管に注意する。','次亜塩素酸ナトリウム':'酸化作用をもつ塩素系消毒剤。有機物で効果が低下しやすく、酸性剤と混ぜない。','次亜塩素酸':'水溶液中で消毒作用に関与する化学種。製品の濃度・pH・使用法を確認する。','グルコン酸クロルヘキシジン':'ビグアナイド系の殺菌消毒成分。適用部位、濃度、禁忌は製品の公式情報に従う。','過酸化水素':'酸化剤。消毒、パーマ第2剤、酸化染毛剤、脱色剤などで用途が異なる。','過酢酸':'強い酸化作用をもつ消毒・滅菌用成分。皮膚への日常的な塗布用ではない。','グリセリン':'水溶性の多価アルコールで、吸湿性を利用した保湿成分。','ヒアルロン酸':'高い保水性をもつグリコサミノグリカン。化粧品では保湿目的に用いられる。','ワセリン':'炭化水素系の油性成分。皮膚表面を覆い、水分蒸散を抑える。','防腐剤':'製品中の微生物増殖を抑え、使用期間中の品質を保つ。酸化防止剤とは目的が異なる。','酸化防止剤':'油性成分等の酸化による変臭・変色・品質低下を抑える。防腐剤とは対象が異なる。','界面活性剤':'親水基と親油基をもち、洗浄・乳化・分散・可溶化等に用いる。','陰イオン界面活性剤':'水中で陰電荷を帯び、洗浄・起泡性を利用してシャンプー等に用いられる。','陽イオン界面活性剤':'水中で陽電荷を帯び、毛髪への吸着、柔軟化、帯電防止等に用いられる。','非イオン界面活性剤':'水中でイオンに解離せず、乳化・可溶化・分散等に用いられる。','両性界面活性剤':'分子内に陽イオン性部位と陰イオン性部位をもち、pH等で性質が変化する。','パーマ剤':'還元と酸化を利用して毛髪の形を変化・固定する。第1剤と第2剤の役割を混同しない。','還元剤':'パーマでは毛髪ケラチンのジスルフィド結合を還元し、形を変えやすくする。','酸化剤':'電子を受け取る側の試薬。パーマ第2剤では還元された結合を酸化して形を固定する。','チオグリコール酸':'チオール基をもつ還元成分。パーマ第1剤等に用いられる。','ブロム酸ナトリウム':'酸化成分。パーマ第2剤に用いられる。','パーマ第1剤':'主に還元作用でジスルフィド結合を切断し、毛髪を変形しやすくする。','パーマ第2剤':'主に酸化作用で結合の再形成を促し、毛髪の形を固定する。'
};
const BODY={
 '皮膚':'表皮・真皮・皮下組織からなり、防御、知覚、体温調節等を担う。','表皮':'皮膚の最外層。角化細胞が主体で、血管をもたない。','真皮':'表皮の下にある結合組織層。コラーゲン・エラスチン、血管、神経、皮膚付属器を含む。','皮下組織':'真皮の下の層。脂肪組織を多く含み、保温、緩衝、エネルギー貯蔵に関与する。','角質層':'表皮の最外層。脱核した角化細胞と細胞間脂質がバリアを形成する。','透明層':'厚い皮膚の手掌・足底で明瞭な、角質層と顆粒層の間の層。','顆粒層':'角質層の下に位置し、角化とバリア形成に関与する。','有棘層':'基底層と顆粒層の間。角化細胞同士がデスモソームで強く結合する。','基底層':'表皮の最深部。基底細胞の分裂とメラノサイトからのメラニン受渡しが行われる。','メラノサイト':'表皮基底層に主に存在し、メラニンを産生する細胞。','ランゲルハンス細胞':'表皮に存在する抗原提示細胞で、皮膚免疫に関与する。','線維芽細胞':'真皮でコラーゲン、エラスチン、細胞外基質の産生に関与する。','皮脂腺':'毛包に開口することが多く、皮脂を分泌して皮膚・毛髪表面の保護に関与する。','汗腺':'汗を分泌する皮膚付属器。エクリン腺とアポクリン腺は開口部位と機能が異なる。','エクリン腺':'ほぼ全身に分布し皮膚表面に開口。主に体温調節の発汗を担う。','アポクリン腺':'腫窩等に分布し毛包に開口。分泌物が皮膚常在菌で分解されるとにおいに関与する。','毛髪':'皮膚外の毛幹と皮膚内の毛根に分けられ、主成分はケラチンである。','毛幹':'皮膚表面から外に出ている毛髪部分。毛小皮、毛皮質、毛髄質からなる。','毛根':'皮膚内にある毛髪部分。下端は毛球を形成する。','毛球':'毛根下端の膨らんだ部分。毛母細胞が毛乳頭を囲む。','毛乳頭':'毛球内に入り込む結合組織。毛細血管を介して毛母細胞の増殖に必要な環境を支える。','毛母細胞':'毛球で活発に分裂し、角化して毛髪を形成する。','毛包':'毛根を包む皮膚内の袋状構造。皮脂腺等と関係する。','毛小皮':'毛幹の最外層。鱗片状の細胞が重なり、内部を保護する。','キューティクル':'毛小皮の英語由来名。毛幹最外層で内部を保護する。','毛皮質':'毛幹の大部分を占め、強度、弾性、色に関与する。','コルテックス':'毛皮質の英語由来名。ケラチン繊維とメラニン顆粒を含む。','毛髄質':'毛幹中心部にみられることがある層。細い毛髪では存在しないことがある。','メデュラ':'毛髄質の英語由来名。毛幹の中心部。','ケラチン':'毛髪・爪・角質層などを構成する繊維性タンパク質。','シスチン':'システイン2分子がジスルフィド結合した形。毛髪ケラチンの強度とパーマ反応に関与する。','メラニン':'メラノサイトが産生する色素。皮膚と毛髪の色、紫外線防御に関与する。','ユーメラニン':'黒色から褐色系のメラニン。','フェオメラニン':'黄色から赤褐色系のメラニン。','毛周期':'成長期・退行期・休止期を繰り返す毛包の周期。','成長期':'毛母細胞が活発に増殖し、毛髪が成長する時期。','退行期':'毛包の成長が停止し、退縮する移行期。','休止期':'毛包の活動が休止する時期。その後の新しい成長に伴って旧い毛が脱落する。'
};
const sourceFor=(name)=>Object.keys(ABBR).some(key=>key.length>1&&name.includes(key))?['厚生労働省・JIHS公開資料','https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/kenkou_iryou/kenkou/index.html']:ROLE[name]?['厚生労働省「医薬品・医療機器」','https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/kenkou_iryou/iyakuhin/index.html']:['NCBI Bookshelf：皮膚・毛髪の解剖生理','https://www.ncbi.nlm.nih.gov/books/'];
document.querySelectorAll('details.qa').forEach(detail=>{
 const name=detail.querySelector('.qtext')?.textContent.trim(),answer=detail.querySelector('.answer');if(!name||!answer)return;
 const abbr=ABBR[name]||Object.entries(ABBR).find(([key])=>key.length>1&&name.includes(key))?.[1],role=ROLE[name],body=BODY[name];if(!abbr&&!role&&!body)return;
 const [title,url]=sourceFor(name),parts=[];
 if(abbr)parts.push(`<strong>正式名称：</strong>${abbr[0]}<br><strong>意味：</strong>${abbr[1]}`);
 if(role)parts.push(`<strong>役割・作用：</strong>${role}`);
 if(body)parts.push(`<strong>位置・構造・機能：</strong>${body}`);
 const box=document.createElement('div');box.className='priority-evidence';box.innerHTML=`${parts.join('<br>')}<br><small><a href="${url}" target="_blank" rel="noopener">${title}</a>／基準日 2026-07-16</small>`;answer.appendChild(box);
});
})();
// 用語集本体の大規模HTMLを変更せず、追加監修データを読み込む。
(()=>{const script=document.createElement('script');script.src='glossaryCompleteness.js';document.body.appendChild(script)})();
