const app=document.getElementById('app');
const state={screen:'home',mode:'study',exam:EXAM53,index:0,answers:[],revealed:false};
(()=>{const s=document.createElement('style');s.textContent='.review-matrix{display:grid;grid-template-columns:minmax(7em,auto) 1fr;margin:8px 0;border:1px solid #dfe6f2;border-radius:10px;overflow:hidden}.review-matrix dt,.review-matrix dd{margin:0;padding:8px 10px;border-bottom:1px solid #e8edf5}.review-matrix dt{font-weight:700;background:#f4f7fc}.review-matrix dd{background:#fff}@media(max-width:560px){.review-matrix{grid-template-columns:1fr}}';document.head.appendChild(s)})();
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const correct=(q,a)=>q.neutral||Array.isArray(q.answer)?q.neutral||q.answer.includes(a):a===q.answer;
function header(title,back=true){return `<header class="header">${back?'<button onclick="goBack()" aria-label="戻る">‹</button>':'<span></span>'}<h1>${esc(title)}</h1><a href="../index.html" aria-label="ホーム">⌂</a></header>`}
const examKey=e=>String(e.examKey??e.round);
const examLabel=e=>e.title.replace(' 理容師国家試験','');
const OFFICIAL_ACADEMIC_YEARS={24:2011,25:2011,26:2012,27:2012,28:2013,29:2013,30:2014,31:2014,32:2015,33:2015,34:2016,35:2016,36:2017,37:2017,38:2018,39:2018,40:2019,41:2019,42:2020,43:2020,44:2021,45:2021,46:2022,47:2022,48:2023,49:2023,50:2024,51:2024,52:2025,53:2025};
const academicYear=e=>OFFICIAL_ACADEMIC_YEARS[Number(e.round)]||'年度確認中';
const fullExamTitle=e=>`${academicYear(e)}年度：${e.title}`;
const RELATED_GLOSSARY={
 '53-7':['医薬部外品','化粧品'],'53-21':['消毒用エタノール','次亜塩素酸ナトリウム','紫外線消毒'],'53-22':['次亜塩素酸ナトリウム','塩化ベンザルコニウム'],'53-23':['蒸気消毒','煮沸消毒'],'53-24':['次亜塩素酸ナトリウム'],'53-25':['次亜塩素酸ナトリウム','グルコン酸クロルヘキシジン','塩化ベンザルコニウム'],'53-39':['還元剤','酸化剤','パーマ第1剤','パーマ第2剤'],'53-40':['酸化染毛剤','酸性染毛料','脱色剤']
};
function relatedTerms(q){return RELATED_GLOSSARY[`${state.exam.round}-${q.number}`]||[]}
function relatedGlossaryHtml(q){const terms=relatedTerms(q);return terms.length?`<section class="related-glossary"><h4>関連用語を確認</h4><p>${terms.map(term=>`<a href="../用語集.html#term=${encodeURIComponent(term)}">${esc(term)}</a>`).join('　')}</p></section>`:''}
function home(){return `<main class="shell">${header('過去問',false)}<section class="content">${EXAMS.map(e=>`<section class="card round-card"><span class="round-label">収録済み</span><h2>${esc(fullExamTitle(e))}</h2><div class="round-meta"><span>全${e.count}問</span><span>原本順</span></div><div class="mode-grid"><button class="mode exam" onclick="start('${esc(examKey(e))}','exam')">本試験モード</button><button class="mode study" onclick="start('${esc(examKey(e))}','study')">学習モード</button></div><p class="note">本試験モードでは全問解答後に採点します。学習モードでは1問ごとに正誤を確認できます。</p><p class="source-note">出典：${esc(e.source)}</p></section>`).join('')}</section></main>`}
function start(key,mode){state.screen='quiz';state.exam=EXAMS.find(e=>examKey(e)===String(key))||EXAM53;state.mode=mode;state.index=0;state.answers=Array(state.exam.count).fill(null);state.revealed=false;render()}
function question(){const e=state.exam,q=e.questions[state.index],selected=state.answers[state.index],show=state.mode==='study'&&state.revealed;return `<main class="shell">${header(`${examLabel(e)}　問題${q.number}`)}<section class="content"><div class="progress"><i style="width:${(state.index+1)/e.count*100}%"></i></div><section class="card question-card"><div class="question-meta"><span>${esc(q.category)}</span><span>${state.index+1} / ${e.count}</span></div>${q.stem?`<h2 class="stem">${esc(q.stem)}</h2>`:''}${q.statements?`<div class="statements">${q.statements.map((s,i)=>`<div class="statement"><span>${'abcd'[i]}.</span><span>${esc(s)}</span></div>`).join('')}</div>`:''}${q.image?`<img class="question-image" src="${esc(q.image)}" alt="${esc(examLabel(e))}問題${q.number}">`:''}<div class="choices">${q.choices.map((c,i)=>`<button class="choice ${selected===i?'selected ':''}${show&&correct(q,i)?'correct ':''}${show&&selected===i&&!correct(q,i)?'wrong ':''}" onclick="choose(${i})" ${show?'disabled':''}><em>${i+1}</em><span>${esc(c)}</span></button>`).join('')}</div>${show?feedback(q,selected):''}<button class="next" onclick="next()" ${selected===null?'disabled':''}>${state.index===e.count-1?'採点する':'次の問題へ'}</button><div class="source">原本 PDF ${q.sourcePage}ページ</div></section></section></main>`}
function feedback(q,selected){const ok=correct(q,selected),label=q.neutral?'採点対象外です':ok?'正解です':`正解は ${Array.isArray(q.answer)?q.answer.map(v=>v+1).join(' または '):q.answer+1} です`,legal=q.currentLegalReview?`<h4>現行法令・通知の最終照合</h4><dl class="review-matrix">${Object.entries(q.currentLegalReview).map(([k,v])=>`<dt>${esc(k)}</dt><dd>${esc(v)}</dd>`).join('')}</dl><p><a href="${esc(q.currentLegalUrl)}" target="_blank" rel="noopener">${esc(q.currentLegalSource)}</a></p>`:'',review=q.structuredReview?`<h4>判断の整理</h4><dl class="review-matrix">${Object.entries(q.structuredReview).map(([k,v])=>`<dt>${esc(k)}</dt><dd>${esc(v)}</dd>`).join('')}</dl>`:'',choiceNotes=(q.choiceExplanations||[]).length?`<h4>選択肢別：選ぶ理由・選ばない理由</h4><ol>${q.choiceExplanations.map(x=>`<li>${esc(x)}</li>`).join('')}</ol>`:'',current=q.currentSourceUrl?`<p>現行資料：<a href="${esc(q.currentSourceUrl)}" target="_blank" rel="noopener">${esc(q.currentSourceTitle)}</a></p>`:'';return `<section class="feedback"><h3>${label}</h3><p>${esc(q.explanation)}</p>${legal}${review}${choiceNotes}<p>根拠状態：${esc(q.evidenceStatus)}</p><p>公開資料基準日：${esc(q.reviewDate||'2026-07-16')}／<a href="${esc(q.officialSourceUrl||'https://www.rbc.or.jp/exam/past_question/')}" target="_blank" rel="noopener">公式過去問</a></p>${current}${relatedGlossaryHtml(q)}</section>`}
function choose(i){if(state.mode==='study'&&state.revealed)return;state.answers[state.index]=i;if(state.mode==='study')state.revealed=true;render()}
function next(){if(state.answers[state.index]===null)return;if(state.index===state.exam.count-1){state.screen='result';render();return}state.index++;state.revealed=false;render();scrollTo(0,0)}
function result(){const e=state.exam,graded=e.questions.filter(q=>!q.neutral),correctCount=e.questions.reduce((n,q,i)=>n+(!q.neutral&&correct(q,state.answers[i])?1:0),0),rate=Math.round(correctCount/graded.length*100),passLine=graded.length>=55?33:30,categories=[...new Set(graded.map(q=>q.category))],stats=categories.map(category=>{const rows=e.questions.map((q,i)=>({q,i})).filter(x=>!x.q.neutral&&x.q.category===category),ok=rows.filter(x=>correct(x.q,state.answers[x.i])).length;return{category,total:rows.length,ok,rate:Math.round(ok/rows.length*100)}}),zeroCategories=stats.filter(x=>x.ok===0).map(x=>x.category),passed=correctCount>=passLine&&zeroCategories.length===0,short=Math.max(0,passLine-correctCount),low=stats.filter(x=>x.rate<40).map(x=>x.category),reasons=[],related=[...new Set(e.questions.flatMap(q=>relatedTerms(q)))];if(!passed){if(correctCount<passLine)reasons.push(`合格基準の60％に達していません（あと${short}問）。`);if(zeroCategories.length)reasons.push(`無得点の分野があります：${zeroCategories.join('、')}`);if(low.length)reasons.push(`正答率が特に低い分野があります：${low.join('、')}`)}return `<main class="shell">${header(`${academicYear(e)}年度 第${e.round}回 採点結果`)}<section class="content"><section class="card result"><div class="pass-result ${passed?'passed':'failed'}">${passed?'合格！':'不合格！'}</div><span>総正答数</span><div class="score">${correctCount} / ${graded.length}</div><p class="correct-rate">総正答率 ${rate}％</p><p class="pass-note">合格基準：${passLine}問以上（60％以上）かつ全課目で1点以上${graded.length!==e.count?`／採点対象${graded.length}問`:''}</p><section class="category-results">${stats.map(x=>`<div class="category-row"><span>${esc(x.category)}</span><span>${x.ok} / ${x.total}問　${x.rate}％</span></div>`).join('')}</section>${reasons.length?`<section class="fail-reasons"><h3>不合格になった主な要因</h3><ul>${reasons.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></section>`:''}${related.length?`<section class="related-glossary"><h3>関連用語を確認</h3><p>${related.map(term=>`<a href="../用語集.html#term=${encodeURIComponent(term)}">${esc(term)}</a>`).join('　')}</p></section>`:''}<div class="result-actions"><button onclick="start('${esc(examKey(e))}','${state.mode}')">もう一度</button><button onclick="showHome()">回別一覧へ</button></div></section></section></main>`}
function showHome(){state.screen='home';render();scrollTo(0,0)}
function goBack(){if(state.screen==='home'){location.href='../index.html';return}if(state.screen==='result'){showHome();return}if(state.index>0){state.index--;state.revealed=state.mode==='study'&&state.answers[state.index]!==null;render();return}showHome()}
function render(){app.innerHTML=state.screen==='home'?home():state.screen==='result'?result():question()}
render();
