const app=document.getElementById('app');
const state={screen:'home',mode:'study',exam:EXAM53,index:0,answers:[],revealed:false};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const correct=(q,a)=>q.neutral||Array.isArray(q.answer)?q.neutral||q.answer.includes(a):a===q.answer;
function header(title,back=true){return `<header class="header">${back?'<button onclick="goBack()" aria-label="戻る">‹</button>':'<span></span>'}<h1>${esc(title)}</h1><a href="../index.html" aria-label="ホーム">⌂</a></header>`}
const examKey=e=>String(e.examKey??e.round);
const examLabel=e=>e.title.replace(' 理容師国家試験','');
function home(){return `<main class="shell">${header('過去問',false)}<section class="content">${EXAMS.map(e=>`<section class="card round-card"><span class="round-label">収録済み</span><h2>${esc(e.title)}</h2><div class="round-meta"><span>全${e.count}問</span><span>原本順</span></div><div class="mode-grid"><button class="mode exam" onclick="start('${esc(examKey(e))}','exam')">本試験モード</button><button class="mode study" onclick="start('${esc(examKey(e))}','study')">学習モード</button></div><p class="note">本試験モードでは全問解答後に採点します。学習モードでは1問ごとに正誤を確認できます。</p><p class="source-note">出典：${esc(e.source)}</p></section>`).join('')}</section></main>`}
function start(key,mode){state.screen='quiz';state.exam=EXAMS.find(e=>examKey(e)===String(key))||EXAM53;state.mode=mode;state.index=0;state.answers=Array(state.exam.count).fill(null);state.revealed=false;render()}
function question(){const e=state.exam,q=e.questions[state.index],selected=state.answers[state.index],show=state.mode==='study'&&state.revealed;return `<main class="shell">${header(`${examLabel(e)}　問題${q.number}`)}<section class="content"><div class="progress"><i style="width:${(state.index+1)/e.count*100}%"></i></div><section class="card question-card"><div class="question-meta"><span>${esc(q.category)}</span><span>${state.index+1} / ${e.count}</span></div>${q.stem?`<h2 class="stem">${esc(q.stem)}</h2>`:''}${q.statements?`<div class="statements">${q.statements.map((s,i)=>`<div class="statement"><span>${'abcd'[i]}.</span><span>${esc(s)}</span></div>`).join('')}</div>`:''}${q.image?`<img class="question-image" src="${esc(q.image)}" alt="${esc(examLabel(e))}問題${q.number}">`:''}<div class="choices">${q.choices.map((c,i)=>`<button class="choice ${selected===i?'selected ':''}${show&&correct(q,i)?'correct ':''}${show&&selected===i&&!correct(q,i)?'wrong ':''}" onclick="choose(${i})" ${show?'disabled':''}><em>${i+1}</em><span>${esc(c)}</span></button>`).join('')}</div>${show?feedback(q,selected):''}<button class="next" onclick="next()" ${selected===null?'disabled':''}>${state.index===e.count-1?'採点する':'次の問題へ'}</button><div class="source">原本 PDF ${q.sourcePage}ページ</div></section></section></main>`}
function feedback(q,selected){const ok=correct(q,selected),label=q.neutral?'採点対象外です':ok?'正解です':`正解は ${Array.isArray(q.answer)?q.answer.map(v=>v+1).join(' または '):q.answer+1} です`;return `<section class="feedback"><h3>${label}</h3><p>${esc(q.explanation)}</p><p>根拠状態：${esc(q.evidenceStatus)}</p></section>`}
function choose(i){if(state.mode==='study'&&state.revealed)return;state.answers[state.index]=i;if(state.mode==='study')state.revealed=true;render()}
function next(){if(state.answers[state.index]===null)return;if(state.index===state.exam.count-1){state.screen='result';render();return}state.index++;state.revealed=false;render();scrollTo(0,0)}
function result(){const e=state.exam,graded=e.questions.filter(q=>!q.neutral),correctCount=e.questions.reduce((n,q,i)=>n+(!q.neutral&&correct(q,state.answers[i])?1:0),0),rate=Math.round(correctCount/graded.length*100),passLine=Math.ceil(graded.length*.6),categories=[...new Set(graded.map(q=>q.category))],zeroCategories=categories.filter(category=>!e.questions.some((q,i)=>!q.neutral&&q.category===category&&correct(q,state.answers[i]))),passed=correctCount>=passLine&&zeroCategories.length===0;return `<main class="shell">${header(`${examLabel(e)} 採点結果`)}<section class="content"><section class="card result"><div class="pass-result ${passed?'passed':'failed'}">${passed?'合格！':'不合格！'}</div><span>正答数</span><div class="score">${correctCount} / ${graded.length}</div><p class="correct-rate">正答${rate}％</p><p class="pass-note">合格基準：${passLine}問以上（60％以上）かつ全課目で1点以上${graded.length!==e.count?`／採点対象${graded.length}問`:''}</p>${zeroCategories.length?`<p class="pass-note">0点の課目：${zeroCategories.map(esc).join('、')}</p>`:''}<div class="result-actions"><button onclick="start('${esc(examKey(e))}','${state.mode}')">もう一度</button><button onclick="showHome()">回別一覧へ</button></div></section></section></main>`}
function showHome(){state.screen='home';render();scrollTo(0,0)}
function goBack(){if(state.screen==='home'){location.href='../index.html';return}if(state.screen==='result'){showHome();return}if(state.index>0){state.index--;state.revealed=state.mode==='study'&&state.answers[state.index]!==null;render();return}showHome()}
function render(){app.innerHTML=state.screen==='home'?home():state.screen==='result'?result():question()}
render();
