const app=document.getElementById('app');
const state={screen:'home',mode:'study',exam:EXAM53,index:0,answers:[],revealed:false,endAt:null,timedOut:false};
const PAST_SESSION_KEY='riyoshi_past_exam_session_v1';
let timerHandle=null;
(()=>{const s=document.createElement('style');s.textContent='.review-matrix{display:grid;grid-template-columns:minmax(7em,auto) 1fr;margin:8px 0;border:1px solid #dfe6f2;border-radius:10px;overflow:hidden}.review-matrix dt,.review-matrix dd{margin:0;padding:8px 10px;border-bottom:1px solid #e8edf5}.review-matrix dt{font-weight:700;background:#f4f7fc}.review-matrix dd{background:#fff}@media(max-width:560px){.review-matrix{grid-template-columns:1fr}}';document.head.appendChild(s)})();
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const correct=(q,a)=>q.neutral||Array.isArray(q.answer)?q.neutral||q.answer.includes(a):a===q.answer;
function header(title){return `<header class="header"><span></span><h1>${esc(title)}</h1><span></span></header>${state.screen==='quiz'&&state.endAt?timerHtml():''}`}
const examKey=e=>String(e.examKey??e.round);
const examLabel=e=>e.title.replace(' 理容師国家試験','');
const OFFICIAL_ACADEMIC_YEARS={24:2011,25:2011,26:2012,27:2012,28:2013,29:2013,30:2014,31:2014,32:2015,33:2015,34:2016,35:2016,36:2017,37:2017,38:2018,39:2018,40:2019,41:2019,42:2020,43:2020,44:2021,45:2021,46:2022,47:2022,48:2023,49:2023,50:2024,51:2024,52:2025,53:2025};
const academicYear=e=>OFFICIAL_ACADEMIC_YEARS[Number(e.round)]||'年度確認中';
const fullExamTitle=e=>`${academicYear(e)}年度：${e.title}`;
function pendingPast(){try{const row=JSON.parse(localStorage.getItem(PAST_SESSION_KEY)||'null');return row&&row.endAt>Date.now()?row:null}catch(_){return null}}
function pastModeLabel(e,mode){const row=pendingPast();return row&&String(row.examKey)===examKey(e)&&row.mode===mode?'続きから再開':mode==='exam'?'本試験モード':'学習モード'}
const RELATED_GLOSSARY={
 '53-7':['医薬部外品','化粧品'],'53-21':['消毒用エタノール','次亜塩素酸ナトリウム','紫外線消毒'],'53-22':['次亜塩素酸ナトリウム','塩化ベンザルコニウム'],'53-23':['蒸気消毒','煮沸消毒'],'53-24':['次亜塩素酸ナトリウム'],'53-25':['次亜塩素酸ナトリウム','グルコン酸クロルヘキシジン','塩化ベンザルコニウム'],'53-39':['還元剤','酸化剤','パーマ第1剤','パーマ第2剤'],'53-40':['酸化染毛剤','酸性染毛料','脱色剤']
};
function relatedTerms(q){return RELATED_GLOSSARY[`${state.exam.round}-${q.number}`]||[]}
function relatedGlossaryHtml(q){const terms=relatedTerms(q);return terms.length?`<section class="related-glossary"><h4>関連用語を確認</h4><p>${terms.map(term=>`<a href="../用語集.html#term=${encodeURIComponent(term)}">${esc(term)}</a>`).join('　')}</p></section>`:''}
function home(){return `<main class="shell">${header('理容師国家試験 過去問')}<section class="content"><p class="page-description">第29回～第53回の実過去問</p>${EXAMS.map(e=>`<section class="card round-card"><h2>${esc(fullExamTitle(e))}</h2><div class="round-meta"><span>全${e.count}問</span><span>原本順</span></div><div class="mode-grid"><button class="mode exam" onclick="start('${esc(examKey(e))}','exam')">本試験モード</button><button class="mode study" onclick="start('${esc(examKey(e))}','study')">学習モード</button></div><p class="note">本試験モード：100分・全問解答後に採点<br>学習モード：100分・1問ごとに正誤と解説を確認</p><p class="source-note">出典：${esc(e.source)}</p></section>`).join('')}</section></main>`}
function saveTimedSession(){try{localStorage.setItem(PAST_SESSION_KEY,JSON.stringify({examKey:examKey(state.exam),mode:state.mode,index:state.index,answers:state.answers,revealed:state.revealed,endAt:state.endAt,timedOut:state.timedOut}))}catch(_){}}
function clearTimedSession(){try{localStorage.removeItem(PAST_SESSION_KEY)}catch(_){}}
function start(key,mode){let existing=null;try{existing=JSON.parse(localStorage.getItem(PAST_SESSION_KEY)||'null')}catch(_){}if(existing?.endAt>Date.now()&&String(existing.examKey)===String(key)&&existing.mode===mode){restoreTimedSession();render();return}if(existing?.endAt>Date.now()&&!confirm('未完了の過去問があります。最初から開始しますか？'))return;state.screen='quiz';state.exam=EXAMS.find(e=>examKey(e)===String(key))||EXAM53;state.mode=mode;state.index=0;state.answers=Array(state.exam.count).fill(null);state.revealed=false;state.endAt=Date.now()+100*60*1000;state.timedOut=false;saveTimedSession();render()}
function remainingSeconds(){return state.endAt?Math.max(0,Math.ceil((state.endAt-Date.now())/1000)):0}
function timerHtml(){const seconds=remainingSeconds(),m=Math.floor(seconds/60),s=String(seconds%60).padStart(2,'0'),cls=seconds<=60?' danger':seconds<=600?' caution':'';return `<div class="exam-timer${cls}" role="timer">残り ${m}:${s}</div>`}
function armTimer(){clearInterval(timerHandle);if(state.screen!=='quiz'||!state.endAt)return;timerHandle=setInterval(()=>{const seconds=remainingSeconds(),el=document.querySelector('.exam-timer');if(seconds<=0){clearInterval(timerHandle);finishByTimeout();return}if(el){el.textContent=`残り ${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`;el.className=`exam-timer${seconds<=60?' danger':seconds<=600?' caution':''}`}},1000)}
function finishByTimeout(){if(state.timedOut||state.screen!=='quiz')return;state.timedOut=true;saveTimedSession();alert('制限時間が終了しました');state.screen='result';clearTimedSession();render()}
function restoreTimedSession(){try{const saved=JSON.parse(localStorage.getItem(PAST_SESSION_KEY)||'null');if(!saved||!saved.endAt||!Array.isArray(saved.answers))return false;const exam=EXAMS.find(e=>examKey(e)===String(saved.examKey));if(!exam||saved.answers.length!==exam.count)return false;state.exam=exam;state.mode=saved.mode==='exam'?'exam':'study';state.index=Math.min(Math.max(0,Number(saved.index)||0),exam.count-1);state.answers=saved.answers;state.revealed=!!saved.revealed;state.endAt=Number(saved.endAt);state.timedOut=!!saved.timedOut;state.screen=state.endAt<=Date.now()?'result':'quiz';if(state.screen==='result'){state.timedOut=true;clearTimedSession();setTimeout(()=>alert('制限時間が終了しました'),0)}return true}catch(_){return false}}
function splitCombinationStem(value){
 const text=String(value||'');
 if(!/組合せ/.test(text))return null;
 const re=/([a-d])[.．]?[ \u3000]+/g,labels=[],order='abcd';
 let match,expected=0;
 while((match=re.exec(text))){
  const before=match.index?text[match.index-1]:'';
  if(match[1]===order[expected]&&!/[A-Za-z0-9]/.test(before)){labels.push({index:match.index,end:re.lastIndex});expected++;if(expected===4)break;}
 }
 if(labels.length!==4)return null;
 const intro=text.slice(0,labels[0].index).trim();
 const statements=labels.map((item,i)=>text.slice(item.end,i<3?labels[i+1].index:text.length).trim());
 return intro&&statements.every(Boolean)?{intro,statements}:null;
}
function stemHtml(q){
 if(!q.stem)return '';
 if(q.statements)return `<h2 class="stem">${esc(q.stem)}</h2>`;
 const parsed=splitCombinationStem(q.stem);
 if(!parsed)return `<h2 class="stem">${esc(q.stem)}</h2>`;
 return `<h2 class="stem">${esc(parsed.intro)}</h2><div class="statements">${parsed.statements.map((s,i)=>`<div class="statement"><span>${'abcd'[i]}.</span><span>${esc(s)}</span></div>`).join('')}</div>`;
}
function question(){const e=state.exam,q=e.questions[state.index],selected=state.answers[state.index],show=state.mode==='study'&&state.revealed;return `<main class="shell">${header(`${examLabel(e)}　問題${q.number}`)}<section class="content"><div class="progress"><i style="width:${(state.index+1)/e.count*100}%"></i></div><section class="card question-card"><div class="question-meta"><span>${esc(q.category)}</span><span>${state.index+1} / ${e.count}</span></div>${stemHtml(q)}${q.statements?`<div class="statements">${q.statements.map((s,i)=>`<div class="statement"><span>${'abcd'[i]}.</span><span>${esc(s)}</span></div>`).join('')}</div>`:''}${q.image?`<img class="question-image" src="${esc(q.image)}" alt="${esc(examLabel(e))}問題${q.number}">`:''}<div class="choices">${q.choices.map((c,i)=>`<button class="choice ${selected===i?'selected ':''}${show&&correct(q,i)?'correct ':''}${show&&selected===i&&!correct(q,i)?'wrong ':''}" onclick="choose(${i})" ${show?'disabled':''}><em>${i+1}</em><span>${esc(c)}</span></button>`).join('')}</div>${show?feedback(q,selected):''}<div class="question-actions"><button type="button" onclick="previousQuestion()" ${state.index===0?'disabled':''}>前の問題</button><button class="next" onclick="next()" ${selected===null?'disabled':''}>${state.index===e.count-1?'採点する':'次の問題へ'}</button></div><div class="source">原本 PDF ${q.sourcePage}ページ</div></section></section></main>`}
function feedback(q,selected){const ok=correct(q,selected),label=q.neutral?'採点対象外です':ok?'正解です':`正解は ${Array.isArray(q.answer)?q.answer.map(v=>v+1).join(' または '):q.answer+1} です`,legal=q.currentLegalReview?`<h4>現行法令・通知の最終照合</h4><dl class="review-matrix">${Object.entries(q.currentLegalReview).map(([k,v])=>`<dt>${esc(k)}</dt><dd>${esc(v)}</dd>`).join('')}</dl><p><a href="${esc(q.currentLegalUrl)}" target="_blank" rel="noopener">${esc(q.currentLegalSource)}</a></p>`:'',review=q.structuredReview?`<h4>判断の整理</h4><dl class="review-matrix">${Object.entries(q.structuredReview).map(([k,v])=>`<dt>${esc(k)}</dt><dd>${esc(v)}</dd>`).join('')}</dl>`:'',choiceNotes=(q.choiceExplanations||[]).length?`<h4>選択肢別：選ぶ理由・選ばない理由</h4><ol>${q.choiceExplanations.map(x=>`<li>${esc(x)}</li>`).join('')}</ol>`:'',current=q.currentSourceUrl?`<p>現行資料：<a href="${esc(q.currentSourceUrl)}" target="_blank" rel="noopener">${esc(q.currentSourceTitle)}</a></p>`:'';return `<section class="feedback"><h3>${label}</h3><p>${esc(q.explanation)}</p>${legal}${review}${choiceNotes}<p>根拠状態：${esc(q.evidenceStatus)}</p><p>公開資料基準日：${esc(q.reviewDate||'2026-07-16')}／<a href="${esc(q.officialSourceUrl||'https://www.rbc.or.jp/exam/past_question/')}" target="_blank" rel="noopener">公式過去問</a></p>${current}${relatedGlossaryHtml(q)}</section>`}
function choose(i){if(state.mode==='study'&&state.revealed||state.timedOut)return;state.answers[state.index]=i;if(state.mode==='study')state.revealed=true;saveTimedSession();render()}
function next(){if(state.answers[state.index]===null||state.timedOut)return;if(state.index===state.exam.count-1){state.screen='result';clearTimedSession();render();return}state.index++;state.revealed=false;saveTimedSession();render();scrollTo(0,0)}
function previousQuestion(){if(state.index<=0)return;state.index--;state.revealed=state.mode==='study'&&state.answers[state.index]!==null;saveTimedSession();render();scrollTo(0,0)}
function result(){const e=state.exam,graded=e.questions.filter(q=>!q.neutral),correctCount=e.questions.reduce((n,q,i)=>n+(!q.neutral&&correct(q,state.answers[i])?1:0),0),rate=Math.round(correctCount/graded.length*100),passLine=graded.length>=55?33:30,categories=[...new Set(graded.map(q=>q.category))],stats=categories.map(category=>{const rows=e.questions.map((q,i)=>({q,i})).filter(x=>!x.q.neutral&&x.q.category===category),ok=rows.filter(x=>correct(x.q,state.answers[x.i])).length;return{category,total:rows.length,ok,rate:Math.round(ok/rows.length*100)}}),zeroCategories=stats.filter(x=>x.ok===0).map(x=>x.category),passed=correctCount>=passLine&&zeroCategories.length===0,short=Math.max(0,passLine-correctCount),low=stats.filter(x=>x.rate<40).map(x=>x.category),reasons=[],related=[...new Set(e.questions.flatMap(q=>relatedTerms(q)))];if(!passed){if(correctCount<passLine)reasons.push(`合格基準の60％に達していません（あと${short}問）。`);if(zeroCategories.length)reasons.push(`無得点の分野があります：${zeroCategories.join('、')}`);if(low.length)reasons.push(`正答率が特に低い分野があります：${low.join('、')}`)}return `<main class="shell">${header(`${academicYear(e)}年度 第${e.round}回 採点結果`)}<section class="content"><section class="card result"><div class="pass-result ${passed?'passed':'failed'}">${passed?'合格！':'不合格！'}</div><span>総正答数</span><div class="score">${correctCount} / ${graded.length}</div><p class="correct-rate">総正答率 ${rate}％</p><p class="pass-note">合格基準：${passLine}問以上（60％以上）かつ全課目で1点以上${graded.length!==e.count?`／採点対象${graded.length}問`:''}</p><section class="category-results">${stats.map(x=>`<div class="category-row"><span>${esc(x.category)}</span><span>${x.ok} / ${x.total}問　${x.rate}％</span></div>`).join('')}</section>${reasons.length?`<section class="fail-reasons"><h3>不合格になった主な要因</h3><ul>${reasons.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></section>`:''}${related.length?`<section class="related-glossary"><h3>関連用語を確認</h3><p>${related.map(term=>`<a href="../用語集.html#term=${encodeURIComponent(term)}">${esc(term)}</a>`).join('　')}</p></section>`:''}<div class="result-actions"><button onclick="start('${esc(examKey(e))}','${state.mode}')">もう一度</button><button onclick="showHome()">回別一覧へ</button></div></section></section></main>`}
function showHome(){state.screen='home';clearInterval(timerHandle);render();scrollTo(0,0)}
function pastBack(){if(state.screen==='home')return;if(state.screen==='quiz')saveTimedSession();showHome()}
function render(){app.innerHTML=state.screen==='home'?home():state.screen==='result'?result():question();const back=document.getElementById('pastBack');if(back)back.hidden=state.screen==='home';if(state.screen==='home')app.querySelectorAll('.round-card').forEach((card,index)=>{const exam=EXAMS[index],buttons=card.querySelectorAll('.mode');if(buttons[0])buttons[0].textContent=pastModeLabel(exam,'exam');if(buttons[1])buttons[1].textContent=pastModeLabel(exam,'study')});armTimer()}
restoreTimedSession();render();
